# Generated by Django 6.0.5 on 2026-05-07 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfomodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfomodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfomodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basicinfomodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
