# Generated by Django 6.0.5 on 2026-05-07 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CC_app', '0002_alter_basicinfomodel_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfomodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfomodel',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='basicinfomodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basicinfomodel',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='ConsumedCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('calorie', models.FloatField(null=True)),
                ('created_by', models.DateField(auto_now_add=True, null=True)),
                ('consumed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_calorie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ConsumeCalories',
        ),
    ]
